# Blimp 3D Planning Configuration
# This file contains the planning bounds and parameters specific to blimp navigation

ompl_planner_node:
  ros__parameters:
    # Planning workspace bounds (meters)  
    # These define the search space for the planner - should be larger than your actual room
    # Updated for 9+ meter room dimensions
    bounds_min_x: -16.5     # For 9+ meter room with safety margin
    bounds_max_x: 16.5      # For 9+ meter room with safety margin  
    bounds_min_y: -16.5     # For 9+ meter room with safety margin
    bounds_max_y: 16.5      # For 9+ meter room with safety margin
    bounds_min_z: -5.0      # Allow slightly below ground
    bounds_max_z: 5.0       # Room ceiling height

    # Robot physical parameters
    robot_radius: 0.27      # Realistic blimp size (meters) - forces better paths

    # Safety parameters
    safety_margin_from_ceiling: 0.4  # Distance (meters) to stay below highest obstacle
                                     # Prevents hitting unmapped ceilings (e.g., black surfaces)
    safety_margin_from_floor: 0.3    # Distance (meters) to stay above lowest obstacle
                                     # Prevents hitting unmapped floors (e.g., black surfaces)

    # Planning algorithm parameters
    planning_timeout: 15.0  # Maximum planning time (seconds)
    planner_id: "RRTConnect"  # Options: RRTConnect, RRTstar

    # Path post-processing
    enable_path_simplification: true   # Enable path shortcutting
    enable_path_smoothing: true        # Enable B-spline smoothing  
    max_simplification_steps: 50       # Reduced to keep more waypoints
    min_waypoint_distance: 0.5         # Minimum distance between waypoints (meters)

    # Frame configuration
    global_frame: "map"        # Global reference frame
    robot_frame: "camera_link" # Robot camera frame

# Advanced planning parameters (optional)
# state_validity_checker:
#   clearance_threshold: 0.1    # Minimum clearance required (meters)
#   unknown_space_treatment: "free"  # How to treat unknown space: "free" or "occupied"

# Optimization objectives (for RRTstar)
# optimization_objective: "PathLength"  # Options: PathLength, MaximizeMinClearance